-- 001 · Lo schema di partenza, per PostgreSQL.
--
-- È lo stesso schema di `migrazioni/001_iniziale.sql`: stesse tabelle, stesse
-- colonne, stessi vincoli, stessi indici. Cambia solo quello che i due
-- database scrivono diverso, e sono quattro cose:
--
-- 1. **`BIGINT` per i tempi.** È la differenza che fa più male, e non si vede
--    finché non è tardi: in SQLite `INTEGER` è a 64 bit, in PostgreSQL è a 32
--    e arriva a 2.147.483.647. I nostri tempi sono millisecondi
--    (`Date.now()`, oggi 1.788.261.519.572): in un `INTEGER` di PostgreSQL non
--    ci starebbero, e ogni salvataggio schianterebbe. Stesso motivo per
--    `stream`: una carriera lunga ci arriva.
-- 2. **Le chiavi che si contano da sole**: `INTEGER PRIMARY KEY AUTOINCREMENT`
--    è di SQLite; qui è `GENERATED BY DEFAULT AS IDENTITY`.
-- 3. **`REAL` è a 32 bit** in PostgreSQL: lo slancio dei bot vuole
--    `DOUBLE PRECISION`, che è quello che SQLite chiama REAL.
-- 4. **`TEXT` senza limite** va bene in tutti e due, e la lunghezza del nome
--    resta un `CHECK`, non un `VARCHAR(22)`: così la regola sta scritta una
--    volta sola e uguale.
--
-- Gli indici parziali (`WHERE ...`) e quelli su un'espressione (`lower(nome)`)
-- PostgreSQL li sa fare uguale: quelli si copiano tali e quali.

-- ==================== CHI SEI ====================

CREATE TABLE account (
  id               TEXT    PRIMARY KEY,
  email            TEXT,
  email_confermata INTEGER NOT NULL DEFAULT 0,
  stato            TEXT    NOT NULL DEFAULT 'attivo'
                           CHECK (stato IN ('attivo','sospeso','cancellato')),
  lingua           TEXT    NOT NULL DEFAULT 'it',
  paese            TEXT,
  creato           BIGINT  NOT NULL,
  visto            BIGINT  NOT NULL,
  cancellato       BIGINT
);
CREATE UNIQUE INDEX account_email ON account (lower(email)) WHERE email IS NOT NULL;
CREATE INDEX account_visto ON account (visto DESC) WHERE cancellato IS NULL;

-- con che cosa entri: Steam, Apple, Google, la mail, o il dispositivo e basta
CREATE TABLE identita (
  id           TEXT    PRIMARY KEY,
  account_id   TEXT    NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  tipo         TEXT    NOT NULL CHECK (tipo IN ('steam','apple','google','email','ospite')),
  id_esterno   TEXT    NOT NULL,
  segreto_hash TEXT,
  creato       BIGINT  NOT NULL,
  usato        BIGINT,
  UNIQUE (tipo, id_esterno)
);
CREATE INDEX identita_account ON identita (account_id);

-- da dove giochi: una riga per sessione aperta, il gettone sta solo come hash
CREATE TABLE dispositivo (
  id             TEXT    PRIMARY KEY,
  account_id     TEXT    NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  piattaforma    TEXT    NOT NULL DEFAULT 'web'
                         CHECK (piattaforma IN ('windows','mac','linux','ios','android','web')),
  nome           TEXT,
  token_hash     TEXT    NOT NULL,
  versione_gioco TEXT,
  creato         BIGINT  NOT NULL,
  visto          BIGINT  NOT NULL,
  revocato       BIGINT
);
CREATE UNIQUE INDEX dispositivo_token ON dispositivo (token_hash);
CREATE INDEX dispositivo_account ON dispositivo (account_id) WHERE revocato IS NULL;

-- ==================== CHI C'È IN CLASSIFICA ====================

CREATE TABLE artista (
  id            TEXT    PRIMARY KEY,
  account_id    TEXT    REFERENCES account(id) ON DELETE SET NULL,   -- NULL = è un bot
  bot           INTEGER NOT NULL DEFAULT 0,
  nome          TEXT    NOT NULL CHECK (length(nome) BETWEEN 2 AND 22),
  citta         TEXT    NOT NULL,
  genere        TEXT    NOT NULL,
  storia        TEXT    NOT NULL DEFAULT '',
  seed          BIGINT  NOT NULL DEFAULT 0,
  stream        BIGINT  NOT NULL DEFAULT 0 CHECK (stream >= 0),
  fan           BIGINT  NOT NULL DEFAULT 0 CHECK (fan >= 0),
  livello       INTEGER NOT NULL DEFAULT 1,
  fase          INTEGER NOT NULL DEFAULT 0,
  uscite        INTEGER NOT NULL DEFAULT 0,
  deal          INTEGER NOT NULL DEFAULT 0,
  ultima_titolo TEXT,
  ultima_seed   BIGINT  NOT NULL DEFAULT 0,
  chiave_hash   TEXT,                       -- solo per i client vecchi, prima degli account
  creato        BIGINT  NOT NULL,
  punteggio     BIGINT,                     -- quando ha mandato l'ultimo punteggio. NULL = mai
  ritirato      BIGINT,
  CHECK ( (bot = 1 AND account_id IS NULL) OR (bot = 0) )
);
CREATE UNIQUE INDEX artista_nome ON artista (lower(nome)) WHERE ritirato IS NULL;
CREATE INDEX artista_classifica ON artista (stream DESC, creato) WHERE ritirato IS NULL;
CREATE INDEX artista_account ON artista (account_id);

-- le rotelle dei soli bot, fuori da artista perché un giocatore non le ha
CREATE TABLE bot_stato (
  artista_id TEXT             PRIMARY KEY REFERENCES artista(id) ON DELETE CASCADE,
  slancio    DOUBLE PRECISION NOT NULL DEFAULT 0,
  caldo      INTEGER          NOT NULL DEFAULT 0,
  carattere  TEXT             NOT NULL DEFAULT 'normale'
                              CHECK (carattere IN ('normale','costante','esplosivo','meteora'))
);

-- ==================== IL SALVATAGGIO IN CLOUD ====================

CREATE TABLE carriera (
  id              TEXT    PRIMARY KEY,
  account_id      TEXT    NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  artista_id      TEXT    REFERENCES artista(id) ON DELETE SET NULL,
  slot            INTEGER NOT NULL CHECK (slot BETWEEN 1 AND 3),
  stato           TEXT    NOT NULL,
  versione_stato  INTEGER NOT NULL DEFAULT 2,
  versione_gioco  TEXT    NOT NULL DEFAULT '',
  settimana_gioco INTEGER NOT NULL DEFAULT 1,
  anno_gioco      INTEGER NOT NULL DEFAULT 1,
  byte            BIGINT  NOT NULL DEFAULT 0,
  creato          BIGINT  NOT NULL,
  aggiornato      BIGINT  NOT NULL,
  UNIQUE (account_id, slot)
);
CREATE INDEX carriera_artista ON carriera (artista_id);

-- ==================== IL TEMPO DEL MONDO ====================

CREATE TABLE stagione (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome   TEXT    NOT NULL,
  inizio BIGINT  NOT NULL,
  fine   BIGINT,
  stato  TEXT    NOT NULL DEFAULT 'corrente' CHECK (stato IN ('corrente','chiusa'))
);

CREATE TABLE settimana (
  numero      INTEGER PRIMARY KEY,
  stagione_id INTEGER NOT NULL REFERENCES stagione(id),
  iniziata    BIGINT  NOT NULL,
  chiusa      BIGINT,
  artisti     INTEGER NOT NULL DEFAULT 0,
  giocatori   INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX settimana_stagione ON settimana (stagione_id, numero DESC);

-- ==================== LO STORICO ====================

CREATE TABLE punteggio_settimana (
  artista_id TEXT    NOT NULL REFERENCES artista(id) ON DELETE CASCADE,
  settimana  INTEGER NOT NULL REFERENCES settimana(numero) ON DELETE CASCADE,
  stream     BIGINT  NOT NULL CHECK (stream >= 0),
  fan        BIGINT  NOT NULL DEFAULT 0,
  livello    INTEGER NOT NULL DEFAULT 1,
  fase       INTEGER NOT NULL DEFAULT 0,
  uscite     INTEGER NOT NULL DEFAULT 0,
  deal       INTEGER NOT NULL DEFAULT 0,
  limato     INTEGER NOT NULL DEFAULT 0,
  origine    TEXT    NOT NULL DEFAULT 'client' CHECK (origine IN ('client','server','rettifica')),
  ip_hash    TEXT,
  inviato    BIGINT  NOT NULL,
  PRIMARY KEY (artista_id, settimana)
);
CREATE INDEX punteggio_settimana_idx ON punteggio_settimana (settimana);

CREATE TABLE classifica_posizione (
  settimana  INTEGER NOT NULL REFERENCES settimana(numero) ON DELETE CASCADE,
  artista_id TEXT    NOT NULL REFERENCES artista(id) ON DELETE CASCADE,
  pos        INTEGER NOT NULL CHECK (pos > 0),
  stream     BIGINT  NOT NULL,
  delta      INTEGER,
  PRIMARY KEY (settimana, artista_id)
);
CREATE INDEX classifica_pos ON classifica_posizione (settimana, pos);
CREATE INDEX classifica_artista ON classifica_posizione (artista_id, settimana DESC);

-- ==================== QUELLO CHE GIRA ====================

CREATE TABLE notizia (
  id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  settimana  INTEGER NOT NULL REFERENCES settimana(numero) ON DELETE CASCADE,
  artista_id TEXT    REFERENCES artista(id) ON DELETE CASCADE,
  tipo       TEXT    NOT NULL CHECK (tipo IN ('uscita','firma','sparizione','ingresso','ritiro','rivalita','traguardo')),
  testo      TEXT    NOT NULL,
  creato     BIGINT  NOT NULL
);
CREATE INDEX notizia_settimana ON notizia (settimana DESC, id DESC);

CREATE TABLE relazione (
  id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artista_id   TEXT    NOT NULL REFERENCES artista(id) ON DELETE CASCADE,
  altro_id     TEXT    NOT NULL REFERENCES artista(id) ON DELETE CASCADE,
  tipo         TEXT    NOT NULL CHECK (tipo IN ('rivale','feat','amico','crew')),
  grado        INTEGER NOT NULL DEFAULT 1 CHECK (grado BETWEEN 1 AND 6),
  da_settimana INTEGER NOT NULL REFERENCES settimana(numero),
  nota         TEXT,
  creato       BIGINT  NOT NULL,
  CHECK (artista_id <> altro_id),
  UNIQUE (artista_id, altro_id, tipo)
);
CREATE INDEX relazione_altro ON relazione (altro_id);

-- ==================== I TRAGUARDI ====================

CREATE TABLE traguardo (
  codice         TEXT PRIMARY KEY,
  nome           TEXT NOT NULL,
  descrizione    TEXT NOT NULL,
  nascosto       INTEGER NOT NULL DEFAULT 0,
  codice_steam   TEXT,
  codice_ios     TEXT,
  codice_android TEXT
);

CREATE TABLE artista_traguardo (
  artista_id TEXT    NOT NULL REFERENCES artista(id) ON DELETE CASCADE,
  codice     TEXT    NOT NULL REFERENCES traguardo(codice) ON DELETE CASCADE,
  settimana  INTEGER REFERENCES settimana(numero),
  ottenuto   BIGINT  NOT NULL,
  spinto     BIGINT,
  PRIMARY KEY (artista_id, codice)
);
CREATE INDEX traguardo_da_spingere ON artista_traguardo (spinto) WHERE spinto IS NULL;

-- ==================== L'ANTI-IMBROGLIO ====================

CREATE TABLE sospetto (
  id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artista_id TEXT    NOT NULL REFERENCES artista(id) ON DELETE CASCADE,
  tipo       TEXT    NOT NULL CHECK (tipo IN ('salto','frequenza','impossibile','doppione')),
  dettaglio  TEXT    NOT NULL DEFAULT '{}',
  peso       INTEGER NOT NULL DEFAULT 1,
  creato     BIGINT  NOT NULL
);
CREATE INDEX sospetto_artista ON sospetto (artista_id, creato DESC);

CREATE TABLE sanzione (
  id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id TEXT    NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  tipo       TEXT    NOT NULL CHECK (tipo IN ('avviso','fuori_classifica','sospensione')),
  motivo     TEXT    NOT NULL,
  da         BIGINT  NOT NULL,
  a          BIGINT,
  deciso_da  TEXT    NOT NULL DEFAULT 'automatico'
);
CREATE INDEX sanzione_account ON sanzione (account_id, a);

-- ==================== SE E QUANDO CI SARANNO ACQUISTI ====================

CREATE TABLE acquisto (
  id         TEXT    PRIMARY KEY,
  account_id TEXT    NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  negozio    TEXT    NOT NULL CHECK (negozio IN ('steam','apple','google')),
  id_esterno TEXT    NOT NULL,
  prodotto   TEXT    NOT NULL,
  centesimi  BIGINT  NOT NULL,
  valuta     TEXT    NOT NULL DEFAULT 'EUR',
  stato      TEXT    NOT NULL DEFAULT 'pagato' CHECK (stato IN ('pagato','rimborsato','contestato')),
  ricevuta   TEXT,
  creato     BIGINT  NOT NULL,
  UNIQUE (negozio, id_esterno)
);

-- ==================== LO STATO DEL MONDO ====================
-- una riga per cosa: settimana corrente, quando scatta il prossimo giro, ecc.

CREATE TABLE stato (
  chiave TEXT PRIMARY KEY,
  valore TEXT NOT NULL
);
