-- 002 · Le segnalazioni.  (la gemella di `migrazioni/002_segnalazioni.sql`)
--
-- Sugli store un nome d'arte è contenuto scritto dagli utenti e mostrato ad
-- altri utenti: Apple e Google chiedono che ci sia un modo per segnalarlo e
-- qualcuno che lo guardi. Questa è quella coda.

CREATE TABLE segnalazione (
  id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artista_id TEXT    NOT NULL REFERENCES artista(id) ON DELETE CASCADE,
  account_id TEXT    REFERENCES account(id) ON DELETE SET NULL,  -- chi ha segnalato
  motivo     TEXT    NOT NULL CHECK (motivo IN ('nome','storia','imbroglio','altro')),
  nota       TEXT,
  stato      TEXT    NOT NULL DEFAULT 'aperta'
                     CHECK (stato IN ('aperta','accolta','respinta')),
  creato     BIGINT  NOT NULL,
  chiusa     BIGINT,
  UNIQUE (artista_id, account_id, motivo)      -- una segnalazione a testa, non dieci
);
CREATE INDEX segnalazione_aperte ON segnalazione (creato DESC) WHERE stato = 'aperta';
CREATE INDEX segnalazione_artista ON segnalazione (artista_id);

-- Quando un nome viene cambiato d'ufficio si tiene traccia di com'era.
ALTER TABLE artista ADD COLUMN nome_prima TEXT;
