#!/usr/bin/env python3
import hashlib
import importlib.util
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
TARGET = HERE / "audio-analysis-v1-evaluate.py"

spec = importlib.util.spec_from_file_location("fame_v1_eval_test_target", TARGET)
if spec is None or spec.loader is None:
    raise RuntimeError("Unable to load evaluator")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

assert module.bpm_category(120, 120) == "EXACT_METRIC_LEVEL"
assert module.bpm_category(60, 120) == "HALF_TIME"
assert module.bpm_category(240, 120) == "DOUBLE_TIME"
assert module.bpm_category(97, 120) == "OTHER"
assert module.bpm_category(None, 120) == "UNKNOWN"
assert module.bpm_category(123.5, 120, 0.03) == "EXACT_METRIC_LEVEL"
assert module.bpm_category(124, 120, 0.03) == "OTHER"

# Regression: the finalized Human Reference digest is generated by JS.
# 66.0 is intentionally chosen because Python and JSON.stringify may serialize it differently.
with tempfile.TemporaryDirectory() as temp_dir:
    snapshot_path = Path(temp_dir) / "snapshot.json"
    snapshot_path.write_text(
        '{"submission":{"value":66.0}}',
        encoding="utf-8",
    )
    expected = hashlib.sha256(
        '{\n  "value": 66\n}\n'.encode("utf-8")
    ).hexdigest()
    assert module.javascript_submission_digest(snapshot_path) == expected


# Post-hardening Human Reference coverage contract.
valid_window = {
    "position": "EARLY",
    "durationSeconds": 12,
    "beatTimesSeconds": [0.25 + i * 0.5 for i in range(24)],
    "rawTapTimesSeconds": [],
    "quantizationHistory": [],
    "coverage": "COMPLETE",
    "coverageNotes": "",
    "reviewed": True,
}
module.validate_post_hardening_window(valid_window, 120, "TEST:EARLY")

pending = dict(valid_window, coverage="PENDING")
try:
    module.validate_post_hardening_window(pending, 120, "TEST:PENDING")
    raise AssertionError("PENDING coverage should be rejected")
except RuntimeError:
    pass

sparse = dict(valid_window, beatTimesSeconds=[0.25, 0.75], coverageNotes="")
try:
    module.validate_post_hardening_window(sparse, 120, "TEST:SPARSE")
    raise AssertionError("Sparse COMPLETE without note should be rejected")
except RuntimeError:
    pass
module.validate_post_hardening_window(
    dict(sparse, coverageNotes="Long silent passage verified"), 120, "TEST:SPARSE-NOTED"
)

no_beat = dict(
    valid_window,
    beatTimesSeconds=[],
    coverage="NO_BEAT",
    coverageNotes="Entire window verified silent",
)
module.validate_post_hardening_window(no_beat, 120, "TEST:NO-BEAT")

reference = [0.2, 0.7, 1.2, 1.7, 2.2]
identical = module.beat_window_metrics(reference, reference)
assert identical["fMeasure70ms"] == 1.0
assert abs(identical["cemgil40ms"] - 1.0) < 1e-6
assert identical["continuity"]["CMLc"] == 1.0
assert identical["continuity"]["CMLt"] == 1.0
assert identical["continuity"]["AMLc"] == 1.0
assert identical["continuity"]["AMLt"] == 1.0
assert identical["absoluteTimingErrorSeconds"]["median"] == 0.0

shifted = module.beat_window_metrics(reference, [v + 0.08 for v in reference])
assert shifted["fMeasure70ms"] == 0.0

internal = module.section_metrics(
    [5.0, 10.0, 15.0],
    [5.0, 10.0, 15.0],
    20.0,
)
assert internal["primary500ms"]["fMeasure"] == 1.0
assert internal["diagnostic3s"]["fMeasure"] == 1.0
assert internal["primary500ms"]["falsePositives"] == 0
assert internal["primary500ms"]["omissions"] == 0

section_error = module.section_metrics(
    [5.0, 10.0],
    [5.2, 14.0],
    20.0,
)
assert section_error["primary500ms"]["falsePositives"] == 1
assert section_error["primary500ms"]["omissions"] == 1

fake_windows = []
for ref, est in (
    ([0.2, 0.7, 1.2, 1.7], [0.2, 0.7, 1.2, 1.7]),
    ([0.2, 0.7, 1.2, 1.7], [0.2, 0.7, 1.2]),
    ([0.2, 0.7, 1.2, 1.7], [0.2, 0.7, 1.2, 1.7, 2.2]),
):
    metrics = module.beat_window_metrics(ref, est)
    matches = module.mir_eval.util.match_events(ref, est, window=0.07)
    errors = [abs(ref[i] - est[j]) for i, j in matches]
    fake_windows.append({"metrics": metrics, "_errors": errors})

agg = module.family_beat_aggregate(fake_windows)
assert agg["truePositives"] == 11
assert agg["falsePositives"] == 1
assert agg["omissions"] == 1
assert abs(agg["fMeasure70ms"] - (11 / 12)) < 1e-6
assert agg["fMeasure70msMacroMeanAcrossWindowsDiagnostic"] is not None

# Empty candidate boundaries are a known V1 failure mode and must score,
# not crash the evaluator.
empty_sections = module.section_metrics([5.0, 10.0], [], 20.0)
assert empty_sections["primary500ms"]["fMeasure"] == 0.0
assert empty_sections["primary500ms"]["omissions"] == 2
assert empty_sections["boundaryDeviationSeconds"]["referenceToEstimatedMedian"] is None

intervals = module.boundaries_to_intervals([5, 10, 15], 20)
assert intervals.shape == (4, 2)
assert intervals[0].tolist() == [0.0, 5.0]
assert intervals[-1].tolist() == [15.0, 20.0]

print("AUDIO ANALYSIS V1 EVALUATOR TEST: PASS")
print("mir_eval:", module.mir_eval.__version__)
print("Beat F1 @70ms: PASS")
print("Cemgil @40ms: PASS")
print("Continuity CML/AML: PASS")
print("Section F1 @0.5s + 3s: PASS")
print("BPM categories: PASS")
print("Family micro aggregation: PASS")
print("Post-hardening reference coverage contract: PASS")
