/* FAMEpedia — catalogo e controller.
   Documentazione di gioco versionata insieme alle meccaniche. */
"use strict";
(() => {
  const FAME_CATEGORIE = [
    ["tutto","Tutto"],["inizio","Inizia qui"],["tempo","Tempo & vita"],
    ["musica","Musica"],["carriera","Carriera"],["mondo","Mondo"],["online","Online"]
  ];
  const FAME_ARTICOLI = [
    {id:"primi-passi",cat:"inizio",titolo:"Primi passi",breve:"Da zero alla prima settimana senza perderti nei menu.",lead:"Anni di Fame non parte da una superstar. Parti da un artista appena creato, una giornata da riempire e poche risorse da trasformare in una carriera.",sez:[["Da dove cominci","Crea il tuo artista, entra nella carriera e guarda prima di tutto dove sei, quanta energia hai e che ore sono. Non devi fare tutto subito: il gioco premia una crescita costruita nel tempo."],["La prima priorità","Scrivere, trovare o lavorare su un beat e arrivare a una prima uscita ti mette davvero in moto. Lavoro, relazioni e città servono a tenere in piedi quello che costruisci."],["Non esiste una sola strada","Puoi spingere sulla musica, lavorare per mantenerti, costruire rete e presenza oppure prendere rischi. Le scelte si sommano settimana dopo settimana."]],nota:"Se non sai cosa fare, scegli una mossa che faccia avanzare almeno una fra musica, soldi, rete o benessere.",rel:["giornata","energia","scrittura","fasi"]},
    {id:"giornata",cat:"tempo",titolo:"La giornata",breve:"L'orologio va dalle 08:00 alle 04:00 e il tempo è una risorsa vera.",lead:"Il tempo di gioco è separato dall'energia. Ogni azione occupa minuti o ore e la giornata ha un limite reale.",sez:[["L'orologio","Una giornata parte alle 08:00 e arriva fino alle 04:00 del giorno successivo. Se un'azione non entra nel tempo rimasto, non viene troncata a metà."],["Azioni e spostamenti","Scrivere, registrare, lavorare, fare live e spostarti consumano tempo in modo diverso. Annullare un'azione prima di confermarla non deve consumare minuti."],["Eventi","Durante una mossa possono succedere eventi. Alcuni interrompono l'azione e la fanno riprendere dopo: il gioco conserva il punto in cui eri arrivato."]],nota:"Tempo ed energia non sono la stessa cosa: puoi avere energia ma non abbastanza ore, o ore ma essere scarico.",rel:["energia","lucidita","spostamenti"]},
    {id:"energia",cat:"tempo",titolo:"Energia",breve:"Parti con 100: ogni giornata ti chiede di scegliere dove spenderla.",lead:"L'energia misura quanto puoi ancora fare fisicamente e mentalmente. All'inizio la capacità massima è 100.",sez:[["Una risorsa giornaliera","Le attività non pesano tutte allo stesso modo. Una scelta importante può mangiare una parte consistente della giornata anche se l'orologio ti lascerebbe altro spazio."],["Recupero","Il riposo e il passaggio dei giorni ti permettono di recuperare. Gestirla male significa arrivare alle occasioni giuste senza benzina."],["Separata dal tempo","Il clock continua ad avere regole proprie: energia e minuti vengono controllati separatamente."]],nota:"Tenere sempre l'energia a zero non è efficienza: significa toglierti margine quando capita qualcosa che non avevi previsto.",rel:["giornata","benessere","lucidita"]},
    {id:"lucidita",cat:"tempo",titolo:"Lucidità",breve:"Quanto hai la testa dentro la musica, da 0 a 100.",lead:"La lucidità rappresenta la qualità della tua concentrazione creativa.",sez:[["Come sale","Lavorare ai pezzi e restare dentro alla musica può aumentarla."],["Come scende","Turni di lavoro, settimane vuote e tempo saltato possono consumarla."],["Perché conta","Quando trascuri troppo la parte creativa, la carriera continua a muoversi ma tu arrivi peggio alle azioni musicali."]],nota:"Se stai facendo solo soldi ma la musica non avanza, guarda la lucidità.",rel:["scrittura","lavoro","giornata"]},
    {id:"benessere",cat:"tempo",titolo:"Benessere",breve:"La carriera pesa anche fuori dai numeri di stream.",lead:"Il benessere misura quanto stai reggendo la vita che ti sei costruito.",sez:[["Pressione","Tour, lavoro e scelte aggressive possono costare benessere anche quando portano soldi o visibilità."],["Recuperare","Rallentare o scegliere una strada meno redditizia può essere la mossa giusta sul lungo periodo."],["Scelte vere","Alcune prove di carriera guardano anche quanto stai bene, non solo quanti fan hai."]],nota:"Una carriera che cresce mentre il personaggio crolla non è automaticamente una carriera che sta andando bene.",rel:["fasi","energia","lavoro"]},
    {id:"lavoro",cat:"tempo",titolo:"Lavoro e soldi",breve:"Prima che la musica paghi, il tempo ha un prezzo molto concreto.",lead:"All'inizio il denaro non arriva da solo. Lavorare può tenerti a galla, ma occupa ore che non stai usando sulla musica.",sez:[["Turni diversi","I lavori hanno durate diverse: alcuni mangiano mezza giornata, altri quasi tutta."],["Il compromesso","Un turno può risolvere un problema di cassa ma costarti tempo creativo e lucidità."],["Quando cambia","Salendo di carriera, musica, live e opportunità possono spostare il peso delle entrate."]],nota:"Il lavoro è un ponte, non una sconfitta. Il problema nasce quando il ponte diventa l'unica cosa che fai.",rel:["giornata","lucidita","benessere","fasi"]},
    {id:"scrittura",cat:"musica",titolo:"Scrittura",breve:"Le barre sono una delle fondamenta della tua crescita.",lead:"Scrivere alimenta il lato creativo della carriera e fa crescere una delle quattro skill principali dell'artista.",sez:[["Skill","Le quattro skill di base sono scrittura, flow, presenza e rete."],["Costanza","Lavorare ai pezzi nel tempo conta più di una singola sessione perfetta."],["Dalle barre al pezzo","La scrittura da sola non pubblica niente: il materiale deve poi incontrare beat, registrazione e uscita."]],nota:"Una carriera piena di promo con poca musica sotto prima o poi resta senza qualcosa da spingere.",rel:["beat","studio","pubblicazione","skill"]},
    {id:"beat",cat:"musica",titolo:"Beat",breve:"La base su cui trasformare le barre in un brano.",lead:"Il beat è parte del processo musicale, non un semplice cosmetico.",sez:[["Trovare il suono","Non tutto deve funzionare per forza col tuo artista. Il beat giusto è quello che rende credibile il pezzo."],["Tempo","Lavorare su un beat è un'azione con una durata propria nella giornata."],["Studio","Quando idea e base stanno insieme, il passaggio successivo è trasformarle in una registrazione."]],nota:"Non confondere quantità di beat con quantità di brani finiti.",rel:["scrittura","studio","pubblicazione"]},
    {id:"studio",cat:"musica",titolo:"Studio e registrazione",breve:"Registrare, rifinire e portare un'idea fino a una traccia pronta.",lead:"Lo studio è dove il materiale smette di essere soltanto un'idea. Registrazione e mix hanno costi di tempo distinti.",sez:[["Registrare","La registrazione è una delle azioni più lunghe della giornata: pianificala quando hai davvero spazio."],["Mix","Rifinire una traccia richiede altro tempo. Avere registrato non significa automaticamente avere un'uscita pronta."],["Qualità e crescita","Il percorso musicale si intreccia con skill, lucidità e qualità del materiale costruito prima di entrare in studio."]],nota:"Entrare in studio senza tempo sufficiente non forza il gioco a chiudere comunque il lavoro.",rel:["scrittura","beat","pubblicazione","giornata"]},
    {id:"pubblicazione",cat:"musica",titolo:"Pubblicare un pezzo",breve:"Il momento in cui il lavoro entra davvero nella carriera pubblica.",lead:"Pubblicare trasforma una traccia in qualcosa che può generare stream, fan, risultati e conseguenze.",sez:[["Prima dell'uscita","Scrittura, beat, registrazione e rifinitura preparano il terreno."],["Dopo l'uscita","Il pezzo entra nel ciclo della carriera: risultati, promozione, classifiche e prove possono iniziare a leggerlo."],["Catalogo","Una carriera forte non è una sola canzone: col tempo costruisci una storia di uscite."]],nota:"La prima pubblicazione è anche uno dei passaggi che aprono la strada alle prime prove di carriera.",rel:["promo","classifiche","fasi","studio"]},
    {id:"promo",cat:"musica",titolo:"Promo e hype",breve:"Far girare un pezzo senza trasformare la promozione in una stampante infinita.",lead:"La promozione spinge attenzione, ma il gioco tiene memoria di quanto hai già spremuto la stessa settimana.",sez:[["Saturazione","La promo ha una memoria settimanale: continuare a premere la stessa leva non moltiplica all'infinito il risultato."],["Hype","L'hype rappresenta quanto sei caldo in quel momento e ha limiti legati alla fase in cui ti trovi."],["Musica prima di tutto","La promo amplifica qualcosa che esiste: non sostituisce un catalogo."]],nota:"Quando il rendimento cala, cambiare attività può valere più che insistere sullo stesso pulsante.",rel:["pubblicazione","fasi","classifiche"]},
    {id:"skill",cat:"carriera",titolo:"Le quattro skill",breve:"Scrittura, flow, presenza e rete aprono strade diverse.",lead:"Le skill crescono con quello che fai. Alcune prove e scelte controllano direttamente se sei abbastanza forte in una di loro.",sez:[["Scrittura","Quanto reggi quando il peso è sulle parole."],["Flow","Quanto sei pronto quando devi far funzionare le barre in tempo reale."],["Presenza","Quanto conti quando sei davanti a un pubblico."],["Rete","Quanto riesci a muovere opportunità attraverso le persone che conosci."]],nota:"Non esiste una build obbligatoria: alcune prove offrono più di una strada.",rel:["fasi","scrittura","relazioni"]},
    {id:"fasi",cat:"carriera",titolo:"Le 7 fasi",breve:"Da Sconosciuto a GOAT, una prova alla volta.",lead:"La carriera è divisa in sette fasi. Non sali solo accumulando numeri: quando maturano i requisiti arriva una prova con una scelta vera.",sez:[["La scala","Sconosciuto → Rapper esordiente → Rapper emergente → Rapper → Star → Man of the Year → GOAT."],["Le prove","Fan, settimane, uscite, skill, hype, classifica e contratto possono entrare nei requisiti."],["Fallire non chiude la partita","Una prova fallita può imporre un periodo prima del nuovo tentativo e costarti hype, ma la carriera continua."]],nota:"Il gradino successivo è un obiettivo, non un timer automatico.",rel:["skill","classifiche","benessere","promo"]},
    {id:"classifiche",cat:"carriera",titolo:"Classifiche",breve:"Una graduatoria condivisa che mette la tua corsa dentro a un mondo più grande.",lead:"La classifica online confronta la tua carriera con il resto del mondo di Anni di Fame. La posizione conta anche per alcune prove avanzate.",sez:[["Una corsa viva","La graduatoria cambia nel tempo e la tua posizione non è soltanto decorativa."],["Filtri","Il backend supporta viste per città, genere e difficoltà, mantenendo una graduatoria generale."],["Carriera","Arrivare in alto può diventare un requisito concreto per passaggi importanti della scalata."]],nota:"Se il servizio online non risponde, la carriera locale continua comunque.",rel:["fasi","account-cloud","promo"]},
    {id:"spostamenti",cat:"mondo",titolo:"Luoghi e spostamenti",breve:"La città non è un menu: muoversi usa tempo e cambia ciò che puoi fare.",lead:"Le attività vivono in luoghi diversi. Spostarti fa avanzare l'orologio e quindi entra nel costo reale della giornata.",sez:[["Tempo di viaggio","Gli spostamenti avanzano subito il clock e vengono salvati."],["Dove sei conta","Alcune azioni dipendono dal posto in cui ti trovi e dagli orari."],["Pianificare","Fare avanti e indietro senza motivo può bruciare ore utili."]],nota:"Prima di iniziare una mossa lunga, guarda sia dove sei sia quanta giornata ti resta.",rel:["giornata","lavoro","relazioni"]},
    {id:"relazioni",cat:"mondo",titolo:"Relazioni e rete",breve:"Persone, contatti e rivali fanno parte della progressione.",lead:"Anni di Fame tiene traccia del mondo intorno a te: contatti, chat, rivalità e rete possono cambiare opportunità e percezione della carriera.",sez:[["Rete","È una skill vera e può essere decisiva quando un'opportunità dipende da chi conosci."],["Rivali e opps","La parte online può mostrarti chi ti sta intorno e chi stai cercando di superare."],["Telefono","Chat, feed, notizie e obiettivi raccolgono una parte importante della vita sociale e della carriera."]],nota:"Avere numeri senza relazioni può chiuderti alcune strade; avere relazioni senza musica non basta comunque.",rel:["skill","telefono","classifiche"]},
    {id:"telefono",cat:"mondo",titolo:"Il telefono",breve:"Non è un menu secondario: è il punto in cui il mondo ti raggiunge.",lead:"Il telefono raccoglie comunicazioni, notizie, feed e strumenti che raccontano cosa sta succedendo attorno alla tua carriera.",sez:[["Chat","Le conversazioni sono separate dal diario degli eventi: le persone ti scrivono come persone, non come log di sistema."],["Notizie e badge","Le palline rosse tengono memoria di quello che hai già guardato."],["Carriera","Parte del mondo online e delle conseguenze delle tue azioni passa da qui."]],nota:"Se compare un badge, aprire l'app relativa aggiorna ciò che il gioco considera già visto.",rel:["relazioni","classifiche","fasi"]},
    {id:"strada",cat:"mondo",titolo:"La Strada",breve:"Una carriera parallela ad alto rischio, senza spoilerarti il percorso.",lead:"La Strada è un sistema distinto dalla carriera musicale: reputazione, pressione e conseguenze crescono con le scelte che fai.",sez:[["Rischio","Reputazione e heat non raccontano la stessa cosa: crescere in un lato può rendere più pericoloso l'altro."],["Conseguenze","Precedenti, arresti e protezioni esistono nello stato della partita. Le decisioni non spariscono appena chiudi la schermata."],["Convivenza","La carriera criminale non sostituisce quella musicale: le due competono per tempo, soldi e attenzione."]],nota:"FAMEpedia evita volutamente di elencare qui le scorciatoie e gli esiti migliori: quella parte va scoperta giocando.",rel:["giornata","benessere","spostamenti"]},
    {id:"account-cloud",cat:"online",titolo:"Account e cloud",breve:"L'account serve a portarti dietro la carriera, non a sbloccare il gioco.",lead:"Puoi giocare in locale. L'account aggiunge identità online e salvataggio cloud, così una carriera può essere recuperata su un altro dispositivo.",sez:[["Sessione","Quando accedi, il gioco conserva una sessione sul dispositivo. La pagina Account controlla col server che sia ancora valida."],["Cloud","Dalle impostazioni puoi salvare e ripristinare gli slot cloud. Un ripristino conserva prima una copia locale recuperabile."],["Server non disponibile","Se il backend non risponde, classifica, account e cloud si fermano; la partita locale continua."]],nota:"Il pallino accanto ad Account nella landing è verde solo quando la sessione viene confermata dal server.",rel:["slot","classifiche"]},
    {id:"slot",cat:"online",titolo:"Slot e salvataggi",breve:"Tre carriere separate, un account che può portarle con te.",lead:"Gli slot separano le partite locali. Ogni slot conserva la propria carriera e il proprio artista senza mescolarli agli altri.",sez:[["Tre slot","Puoi tenere percorsi diversi sullo stesso dispositivo."],["Locale","La partita viene salvata nel browser. Se cancelli i dati locali senza cloud, cancelli anche quella copia."],["Cloud per slot","Il cloud lavora sullo slot aperto e conserva un backup prima di un ripristino."]],nota:"Account e carriera non sono la stessa cosa: l'account identifica te, lo slot identifica una delle tue partite.",rel:["account-cloud","primi-passi"]}
  ];

  const byId = new Map(FAME_ARTICOLI.map(a => [a.id,a]));
  let cat = "tutto", query = "", ultimoFocus = null;
  const $fp = id => document.getElementById(id);
  const norm = s => String(s || "").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

  function nomeCategoria(id){ const c=FAME_CATEGORIE.find(x=>x[0]===id); return c?c[1]:id; }
  function articoliFiltrati(){
    const q=norm(query).trim();
    return FAME_ARTICOLI.filter(a => {
      if(cat!=="tutto" && a.cat!==cat) return false;
      if(!q) return true;
      return norm([a.titolo,a.breve,a.lead,a.cat].concat(a.sez.flatMap(s=>s)).join(" ")).includes(q);
    });
  }
  function disegnaCategorie(){
    const host=$fp("fp-categorie"); if(!host) return;
    host.innerHTML=FAME_CATEGORIE.map(c=>{
      const n=c[0]==="tutto"?FAME_ARTICOLI.length:FAME_ARTICOLI.filter(a=>a.cat===c[0]).length;
      return '<button class="fp-cat'+(cat===c[0]?' on':'')+'" data-fp-cat="'+c[0]+'"><span>'+c[1]+'</span><i>'+n+'</i></button>';
    }).join("");
  }
  function disegnaLista(){
    const dati=articoliFiltrati(), host=$fp("fp-list"), conta=$fp("fp-count");
    if(conta) conta.textContent=dati.length+(dati.length===1?" voce":" voci");
    if(!host) return;
    if(!dati.length){host.innerHTML='<div class="fp-empty"><b>Nessun risultato.</b><br>Prova una parola più semplice o cambia categoria.</div>';return;}
    host.innerHTML=dati.map(a=>'<button class="fp-card" data-fp-open="'+a.id+'"><span class="fp-card-cat">'+nomeCategoria(a.cat)+'</span><h3>'+a.titolo+'</h3><p>'+a.breve+'</p></button>').join("");
  }
  function home(){
    const h=$fp("fp-home"),v=$fp("fp-article-view"); if(h)h.hidden=false;if(v)v.hidden=true;
    disegnaCategorie();disegnaLista();const main=document.querySelector(".fp-main");if(main)main.scrollTop=0;
  }
  function articolo(id){
    const a=byId.get(id);if(!a)return home();
    const h=$fp("fp-home"),v=$fp("fp-article-view");if(h)h.hidden=true;if(v)v.hidden=false;
    $fp("fp-article-cat").textContent=nomeCategoria(a.cat);$fp("fp-article-title").textContent=a.titolo;$fp("fp-article-lead").textContent=a.lead;
    $fp("fp-copy").innerHTML=a.sez.map(s=>"<h2>"+s[0]+"</h2><p>"+s[1]+"</p>").join("")+(a.nota?'<div class="fp-callout">'+a.nota+'</div>':"");
    const rel=(a.rel||[]).map(x=>byId.get(x)).filter(Boolean);
    $fp("fp-related").innerHTML=rel.length?'<div class="fp-related-label">Continua da qui</div><div class="fp-related-grid">'+rel.map(x=>'<button class="fp-related-btn" data-fp-open="'+x.id+'">'+x.titolo+'</button>').join("")+'</div>':"";
    const main=document.querySelector(".fp-main");if(main)main.scrollTop=0;
  }
  function impostaCategoria(id){if(!FAME_CATEGORIE.some(c=>c[0]===id))id="tutto";cat=id;home();}
  function apri(id){
    const root=$fp("famepedia");if(!root)return;ultimoFocus=document.activeElement;root.hidden=false;root.setAttribute("aria-hidden","false");
    document.body.classList.add("famepedia-aperta");query="";const cerca=$fp("fp-search");if(cerca)cerca.value="";
    if(id)articolo(id);else home();setTimeout(()=>{try{(cerca||$fp("fp-close")).focus();}catch(e){}},0);
  }
  function chiudi(){
    const root=$fp("famepedia");if(!root)return;root.hidden=true;root.setAttribute("aria-hidden","true");document.body.classList.remove("famepedia-aperta");
    try{if(ultimoFocus&&ultimoFocus.focus)ultimoFocus.focus();}catch(e){}
  }
  document.addEventListener("click",e=>{
    const c=e.target.closest("[data-fp-cat]");if(c){impostaCategoria(c.dataset.fpCat);return;}
    const o=e.target.closest("[data-fp-open]");if(o){articolo(o.dataset.fpOpen);return;}
    if(e.target.closest("[data-fp-back]")){home();return;}
    if(e.target.closest("[data-fp-close]")){chiudi();return;}
  });
  const search=$fp("fp-search");
  if(search)search.addEventListener("input",()=>{query=search.value;const h=$fp("fp-home");if(h&&h.hidden)home();else disegnaLista();});
  window.addEventListener("keydown",e=>{
    const root=$fp("famepedia"),aperta=root&&!root.hidden;
    if(aperta&&e.key==="Escape"){e.preventDefault();chiudi();return;}
    if(aperta&&e.key==="/"&&document.activeElement!==search){e.preventDefault();if(search)search.focus();}
  });
  window.FAMEPEDIA={apri,chiudi,articolo,get articoli(){return FAME_ARTICOLI.slice();}};
})();
